[build]
  publish = "dist"
  command = "node scripts/prepare_netlify.js"

[[headers]]
  for = "/Sources/*"
  [headers.values]
    Accept-Ranges = "bytes"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
